version: '2'

services:
  # Test OpenGL is available
  test_glxgears:
    image: rhysmainwaring/sail-sim
    devices:
      - /dev/dri:/dev/dri
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
      - "ROS_HOSTNAME=gazebo"
      - "DISPLAY"
    group_add:
      - video
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: stdbuf -o L glxgears
    restart: always

  # Test gazebo is available.
  # 
  # Issues:
  #   gazebo reports the error:
  # 
  #   VMware: vmw_ioctl_command error Invalid argument.
  # 
  #   For gazebo to run correctly in VMware you need to disable
  #   OpenGL 3.3 support by setting SVGA_VGPU10=0.
  #   See the Gazebo answers discussion and Mesa documentation:
  #   - https://answers.gazebosim.org//question/13214/virtual-machine-not-launching-gazebo/
  #   - https://docs.mesa3d.org/vmware-guest.html#running-opengl-programs
  # 
  test_gazebo:
    image: rhysmainwaring/sail-sim
    devices:
      - /dev/dri:/dev/dri
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
      - "ROS_HOSTNAME=gazebo"
      - "DISPLAY"
      - "SVGA_VGPU10=0"
    group_add:
      - video
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: stdbuf -o L gazebo --verbose
    restart: always
  
